name: CICD

on:
  workflow_dispatch:
    inputs:
      msName:
        type: choice
        required: true
        description: microservice to deploy
        options: 
        - odd
        - even

jobs:
  build:
    name: Build And Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      imageTag: ${{ steps.imageTag.outputs.tag }}
    steps:
      - name: variable
        run: |
           echo "${{ github.event.inputs.msName }}"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: microservices/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ttl.sh/ms:${{ github.ref_name }}.${{ github.sha }}
      - id: imageTag
        run: echo "tag=ttl.sh/ms:${{ github.ref_name }}.${{ github.sha }}" >> "$GITHUB_OUTPUT"
      
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.USER_NAME}}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
              chart_path="/home/ubuntu/git/test/microservices/charts/get-url"
              helm upgrade -i ${{ github.event.inputs.msName }} $chart_path \
              -f $chart_path
              --set image.tag=${{needs.build.outputs.imageTag}} \
              --set fullnameOverride=${{ github.event.inputs.msName }}"          
              '