name: ci

on:
  workflow_dispatch:
    inputs:
      msName:
        description: 'Name of microservice to deploy'
        required: true
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      
      - name: variable
        run: |
           echo ${{ github.event.inputs.msName }}"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: microservices/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ttl.sh/ms:${{ github.ref_name }}.${{ github.sha }}