name: Build Docker Image with Kaniko

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: ls
      run: |
        ls -la
      
    - name: Set up Kaniko
      uses: gcr.io/kaniko-project/executor:latest
      
    - name: Build Docker image
      run: |
        /kaniko/executor \
          --context $(pwd)/numbers_api \
          --dockerfile numbers_api/Dockerfile \
          --destination ttl.sh/moon
